/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe */
        get: operations["universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screener
         * @description Every call in the expiry window with its metrics; finer filters are applied client-side.
         */
        get: operations["screener_api_screener__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Ticker
         * @description Fetch and enrich one ticker (warming the cache). Lets clients show scan progress.
         */
        post: operations["scan_ticker_api_scan__ticker__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Opportunities
         * @description Filter the scanned tickers by the user's goals, score every contract and rank them.
         */
        post: operations["opportunities_api_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Contract
         * @description One call option with the metrics a covered-call seller cares about.
         */
        Contract: {
            /** Contract Symbol */
            contract_symbol: string;
            /** Ticker */
            ticker: string;
            /**
             * Expiration
             * Format: date
             */
            expiration: string;
            /** Days To Expiry */
            days_to_expiry: number;
            /** Strike */
            strike: number;
            /** Bid */
            bid: number;
            /** Ask */
            ask: number;
            /** Mid */
            mid: number;
            /** Spread */
            spread: number;
            /**
             * Static Return Pct
             * @description bid / stock price, in percent
             */
            static_return_pct: number;
            /**
             * Annualized Return Pct
             * @description static return x 365 / days to expiry
             */
            annualized_return_pct: number;
            /**
             * Distance To Strike Pct
             * @description (strike - price) / price, in percent
             */
            distance_to_strike_pct: number;
            /**
             * Breakeven
             * @description stock price minus the premium collected
             */
            breakeven: number;
            /** Volume */
            volume: number;
            /** Open Interest */
            open_interest: number;
            /**
             * Iv Pct
             * @description implied volatility, in percent
             */
            iv_pct: number;
            /**
             * Assignment Prob
             * @description Black-Scholes call delta: approx. probability of finishing in the money
             */
            assignment_prob: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OpportunitiesRequest */
        OpportunitiesRequest: {
            /** Tickers */
            tickers: string[];
            /**
             * Min Static Return Pct
             * @default 1
             */
            min_static_return_pct: number;
            /**
             * Max Days To Expiry
             * @default 45
             */
            max_days_to_expiry: number;
            /**
             * Min Otm Pct
             * @default 2
             */
            min_otm_pct: number;
            weights?: components["schemas"]["Weights"];
            /**
             * Yield Actual Frac
             * @default 0.7
             */
            yield_actual_frac: number;
            /**
             * Top N
             * @default 50
             */
            top_n: number;
        };
        /** OpportunitiesResponse */
        OpportunitiesResponse: {
            /** Scanned */
            scanned: number;
            /** Matched */
            matched: number;
            /** Results */
            results: components["schemas"]["Opportunity"][];
        };
        /** Opportunity */
        Opportunity: {
            /** Contract Symbol */
            contract_symbol: string;
            /** Ticker */
            ticker: string;
            /**
             * Expiration
             * Format: date
             */
            expiration: string;
            /** Days To Expiry */
            days_to_expiry: number;
            /** Strike */
            strike: number;
            /** Bid */
            bid: number;
            /** Ask */
            ask: number;
            /** Mid */
            mid: number;
            /** Spread */
            spread: number;
            /**
             * Static Return Pct
             * @description bid / stock price, in percent
             */
            static_return_pct: number;
            /**
             * Annualized Return Pct
             * @description static return x 365 / days to expiry
             */
            annualized_return_pct: number;
            /**
             * Distance To Strike Pct
             * @description (strike - price) / price, in percent
             */
            distance_to_strike_pct: number;
            /**
             * Breakeven
             * @description stock price minus the premium collected
             */
            breakeven: number;
            /** Volume */
            volume: number;
            /** Open Interest */
            open_interest: number;
            /**
             * Iv Pct
             * @description implied volatility, in percent
             */
            iv_pct: number;
            /**
             * Assignment Prob
             * @description Black-Scholes call delta: approx. probability of finishing in the money
             */
            assignment_prob: number | null;
            /** Price */
            price: number;
            /** Score */
            score: number;
            /** Score Yield */
            score_yield: number;
            /** Score Assignment */
            score_assignment: number;
            /** Score Liquidity */
            score_liquidity: number;
            /** Score Volatility */
            score_volatility: number;
            /** Score Dividend */
            score_dividend: number;
        };
        /** ScanTickerResponse */
        ScanTickerResponse: {
            /** Ticker */
            ticker: string;
            /** Ok */
            ok: boolean;
            /** Contracts */
            contracts: number;
        };
        /** ScreenerResponse */
        ScreenerResponse: {
            /** Ticker */
            ticker: string;
            /** Price */
            price: number;
            /** Open Price */
            open_price: number;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Contracts */
            contracts: components["schemas"]["Contract"][];
        };
        /** TickerMatch */
        TickerMatch: {
            /** Label */
            label: string;
            /** Symbol */
            symbol: string;
        };
        /** UniverseTicker */
        UniverseTicker: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Weights
         * @description Raw Opportunity Score weights (normalized server-side).
         */
        Weights: {
            /**
             * Yield
             * @default 40
             */
            yield: number;
            /**
             * Assign
             * @default 30
             */
            assign: number;
            /**
             * Liq
             * @default 15
             */
            liq: number;
            /**
             * Vol
             * @default 10
             */
            vol: number;
            /**
             * Div
             * @default 5
             */
            div: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseTicker"][];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screener_api_screener__ticker__get: {
        parameters: {
            query?: {
                min_days?: number;
                max_days?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_ticker_api_scan__ticker__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanTickerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opportunities_api_opportunities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunitiesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
